


{"filteredValue":{"id":"initialSellingPriceAmount13","value":8.8,"start":10,"end":20,"remarks":"5x higher multiplier in years 10-20"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh1"}}

{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"plantLifetimeAmount10","value":20,"start":14,"end":20,"remarks":"hideh"}}
{"filteredValue":{"id":"initialSellingPriceAmount13","value":2,"start":1,"end":1,"remarks":""}}
{"filteredValue":{"id":"initialSellingPriceAmount13","value":2.4,"start":2,"end":2,"remarks":""}}

{"filteredValue":{"id":"initialSellingPriceAmount13","value":4.8,"start":15,"end":18,"remarks":""}}

{"filteredValues":[{"id":"plantLifetimeAmount10","remarks":""},{"id":"bECAmount11","remarks":""},{"id":"numberOfUnitsAmount12","remarks":""},{"id":"initialSellingPriceAmount13","remarks":"hi"},{"id":"totalOperatingCostPercentageAmount14","remarks":""},{"id":"engineering_Procurement_and_Construction_EPC_Amount15","remarks":""},{"id":"process_contingency_PC_Amount16","remarks":""},{"id":"project_Contingency_PT_BEC_EPC_PCAmount17","remarks":""},{"id":"use_direct_operating_expensesAmount18","remarks":""},{"id":"use_direct_revenueAmount19","remarks":""},{"id":"depreciationMethodAmount20","remarks":""},{"id":"loanTypeAmount21","remarks":""},{"id":"interestTypeAmount22","remarks":""},{"id":"generalInflationRateAmount23","remarks":""},{"id":"interestProportionAmount24","remarks":""},{"id":"principalProportionAmount25","remarks":""},{"id":"loanPercentageAmount26","remarks":""},{"id":"repaymentPercentageOfRevenueAmount27","remarks":""},{"id":"numberofconstructionYearsAmount28","remarks":""},{"id":"iRRAmount30","remarks":""},{"id":"annualInterestRateAmount31","remarks":""},{"id":"stateTaxRateAmount32","remarks":""},{"id":"federalTaxRateAmount33","remarks":""},{"id":"rawmaterialAmount34","remarks":""},{"id":"laborAmount35","remarks":""},{"id":"utilityAmount36","remarks":""},{"id":"maintenanceAmount37","remarks":""},{"id":"insuranceAmount38","remarks":""},{"id":"vAmount40","remarks":""},{"id":"vAmount41","remarks":""},{"id":"vAmount42","remarks":""},{"id":"vAmount43","remarks":""},{"id":"vAmount44","remarks":""},{"id":"vAmount45","remarks":""},{"id":"vAmount46","remarks":""},{"id":"vAmount47","remarks":""},{"id":"vAmount48","remarks":""},{"id":"vAmount49","remarks":""},{"id":"vAmount50","remarks":""},{"id":"vAmount51","remarks":""},{"id":"vAmount52","remarks":""},{"id":"vAmount53","remarks":""},{"id":"vAmount54","remarks":""},{"id":"vAmount55","remarks":""},{"id":"vAmount56","remarks":""},{"id":"vAmount57","remarks":""},{"id":"vAmount58","remarks":""},{"id":"vAmount59","remarks":""},{"id":"rAmount60","remarks":""},{"id":"rAmount61","remarks":""},{"id":"rAmount62","remarks":""},{"id":"rAmount63","remarks":""},{"id":"rAmount64","remarks":""},{"id":"rAmount65","remarks":""},{"id":"rAmount66","remarks":""},{"id":"rAmount67","remarks":""},{"id":"rAmount68","remarks":""},{"id":"rAmount69","remarks":""},{"id":"rAmount70","remarks":""},{"id":"rAmount71","remarks":""},{"id":"rAmount72","remarks":""},{"id":"rAmount73","remarks":""},{"id":"rAmount74","remarks":""},{"id":"rAmount75","remarks":""},{"id":"rAmount76","remarks":""},{"id":"rAmount77","remarks":""},{"id":"rAmount78","remarks":""},{"id":"rAmount79","remarks":""}]}